<script setup>
import { ref, onMounted, nextTick } from 'vue';import * as echarts from 'echarts';import { Users, WalletCards, MapPinned, Route, Sparkles, ArrowUpRight, CalendarDays, CloudSun, Navigation, Zap } from 'lucide-vue-next';import KpiCard from '../components/KpiCard.vue';import { orders } from '../data/mock'
import { getHangzhouWeather,getCityWeather } from '../services/weather'
import TravelPulse from '../components/TravelPulse.vue'
import TravelGallery from '../components/TravelGallery.vue'
const trend=ref(), source=ref(), weatherCity=ref(localStorage.getItem('weather-city')||'杭州'), weatherLoading=ref(false), weather=ref({temperature:'--',apparent:'--',humidity:'--',condition:'加载中',wind:'--',windSpeed:'--',time:'--',live:false});
const changeWeather=async city=>{weatherLoading.value=true;localStorage.setItem('weather-city',city);weather.value=await getCityWeather(city);weatherLoading.value=false}
onMounted(async()=>{weather.value=await getHangzhouWeather();await nextTick();const c=echarts.init(trend.value);c.setOption({grid:{left:18,right:18,top:28,bottom:22,containLabel:true},tooltip:{trigger:'axis',backgroundColor:'#10213d',borderColor:'#29405f',textStyle:{color:'#fff'}},legend:{data:['游客量','订单量'],right:12,textStyle:{color:'#6d7b91'}},xAxis:{type:'category',data:['周一','周二','周三','周四','周五','周六','周日'],axisLine:{show:false},axisTick:{show:false},axisLabel:{color:'#8b97a9'}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#edf1f6'}},axisLabel:{color:'#a0a9b8'}},series:[{name:'游客量',type:'line',smooth:true,data:[320,410,390,560,680,910,840],symbol:'circle',symbolSize:7,lineStyle:{width:3,color:'#16b8a6'},itemStyle:{color:'#16b8a6'},areaStyle:{color:new echarts.graphic.LinearGradient(0,0,0,1,[{offset:0,color:'#16b8a633'},{offset:1,color:'#16b8a600'}])}},{name:'订单量',type:'line',smooth:true,data:[180,240,210,330,420,610,570],symbol:'none',lineStyle:{width:2,color:'#7c6cf2'}}]});const d=echarts.init(source.value);d.setOption({tooltip:{trigger:'item'},series:[{type:'pie',radius:['58%','78%'],center:['50%','48%'],label:{show:false},data:[{value:42,name:'小红书',itemStyle:{color:'#ff6b7a'}},{value:28,name:'抖音',itemStyle:{color:'#191d2b'}},{value:18,name:'自然搜索',itemStyle:{color:'#16b8a6'}},{value:12,name:'其他',itemStyle:{color:'#dce3ec'}}]}]});window.addEventListener('resize',()=>{c.resize();d.resize()})})
</script>
<template><div class="dashboard">
 <div class="welcome"><div><span><Sparkles :size="15"/> 今日运营简报</span><h2>早上好，探索者 👋</h2><p>{{weather.city||weatherCity}}今日{{weather.condition}}，体感 {{weather.apparent}}°C。共有 <b>18 条新行程</b> 等待审核。</p></div><div class="weather live-weather" :class="{loading:weatherLoading}"><CloudSun :size="38"/><div><b>{{weather.temperature}}°C</b><small><el-select v-model="weatherCity" @change="changeWeather" class="weather-switch"><el-option v-for="c in ['杭州','上海','北京','西安','厦门','丽江','成都','广州']" :label="c" :value="c"/></el-select> · {{weather.condition}}</small></div><i></i><div><b>{{weather.wind}} {{weather.windSpeed}} km/h</b><small>湿度 {{weather.humidity}}% · {{weather.time}} <em :class="{live:weather.live}">{{weather.live?'LIVE':'离线'}}</em></small></div></div></div>
 <div class="kpi-grid"><KpiCard label="累计服务游客" value="128,640" change="12.8%" :icon="Users" color="#16b8a6" sub="本月新增 8,429 人"/><KpiCard label="本月交易额" value="¥ 2,846,580" change="18.2%" :icon="WalletCards" color="#7c6cf2" sub="目标完成率 86%"/><KpiCard label="在营目的地" value="216" change="5.4%" :icon="MapPinned" color="#f59e0b" sub="覆盖全国 68 座城市"/><KpiCard label="AI 生成行程" value="36,982" change="24.6%" :icon="Route" color="#f25f7b" sub="平均生成耗时 1.2s"/></div>
 <TravelPulse/>
 <TravelGallery/>
 <div class="dash-grid"><div class="card trend-card"><div class="card-title"><div><small>近 7 天趋势</small><h3>游客与订单增长</h3></div><el-segmented :options="['7天','30天','季度']" value="7天" size="small"/></div><div ref="trend" class="chart"></div></div><div class="card ai-card"><div class="ai-glow"></div><span><Zap :size="14"/> AI INSIGHT</span><h3>本周值得关注</h3><p>“非遗体验 + 夜游”组合搜索量环比增长 <b>41%</b>，建议提高西安、泉州相关产品曝光。</p><div class="insight-stat"><div><small>预测转化提升</small><b>+18.6%</b></div><div class="ring"><span>86</span></div></div><router-link to="/analytics">查看完整洞察 <ArrowUpRight :size="15"/></router-link></div></div>
 <div class="dash-grid bottom"><div class="card orders-card"><div class="card-title"><div><small>实时动态</small><h3>最新订单</h3></div><router-link to="/orders">查看全部</router-link></div><table><thead><tr><th>订单 / 游客</th><th>产品</th><th>金额</th><th>状态</th></tr></thead><tbody><tr v-for="o in orders.slice(0,4)" :key="o.id"><td><b>{{o.user}}</b><small>{{o.id}}</small></td><td>{{o.product}}</td><td><b>¥{{o.amount.toLocaleString()}}</b></td><td><span :class="['status',o.status]">{{o.status}}</span></td></tr></tbody></table></div><div class="card source-card"><div class="card-title"><div><small>渠道构成</small><h3>游客来源</h3></div></div><div class="source-wrap"><div ref="source" class="donut"></div><div class="donut-center"><b>12.8k</b><small>访问量</small></div></div><div class="legend"><span><i style="background:#ff6b7a"></i>小红书 42%</span><span><i style="background:#191d2b"></i>抖音 28%</span><span><i style="background:#16b8a6"></i>搜索 18%</span></div></div></div>
</div></template>
