<script setup>
import {ref,computed,watch} from 'vue'
import {useRoute} from 'vue-router'
import {Users,FileText,MessagesSquare,ShieldCheck,Plus,Search,Send,CheckCircle2,Clock3,AlertTriangle,MoreHorizontal,Pencil,Trash2,Eye} from 'lucide-vue-next'
import {ElMessage,ElMessageBox} from 'element-plus'
const route=useRoute(),active=ref('游客管理'), dialog=ref(false), editing=ref(null), query=ref('')
watch(()=>route.query.q,v=>{if(v){active.value='游客管理';query.value=String(v)}},{immediate:true})
const menu=[['游客管理',Users],['内容发布',FileText],['服务工单',MessagesSquare],['角色权限',ShieldCheck]]
const permissionGroups=[{name:'目的地资源',items:['景点查看','景点新增','景点编辑','景点下架']},{name:'订单业务',items:['订单查看','订单新增','订单编辑','订单确认','订单退款','订单删除']},{name:'游客运营',items:['游客查看','游客新增','游客编辑','游客禁用']},{name:'内容与工单',items:['内容发布','内容编辑','内容删除','工单受理','工单流转','工单删除']},{name:'数据与系统',items:['数据大屏','数据导出','角色配置','操作日志','系统参数','账号审计']}]
const allPermissions=permissionGroups.flatMap(x=>x.items)
const defaults={
 users:[{id:1,name:'林晓雨',phone:'138****6208',level:'星耀会员',trips:12,spent:28680,status:'正常'},{id:2,name:'陈星',phone:'186****3901',level:'金卡会员',trips:8,spent:16320,status:'正常'},{id:3,name:'周亦辰',phone:'177****1056',level:'银卡会员',trips:5,spent:8860,status:'正常'},{id:4,name:'苏小',phone:'159****8123',level:'普通会员',trips:2,spent:2380,status:'关注'}],
 contents:[{id:11,title:'夏日避暑目的地榜单',type:'攻略专题',views:'12.6k',status:'已发布'},{id:12,title:'跟着非遗去旅行',type:'文化专题',views:'17.6k',status:'已发布'},{id:13,title:'城市夜游新玩法',type:'玩法指南',views:'22.6k',status:'草稿'},{id:14,title:'毕业旅行灵感地图',type:'主题活动',views:'27.6k',status:'已发布'}],
 tickets:[{id:'TK20260621',title:'订单退款进度咨询',user:'林晓雨',priority:'紧急',status:'待受理'},{id:'TK20260622',title:'行程日期修改',user:'陈星',priority:'普通',status:'待受理'},{id:'TK20260623',title:'景区入园码异常',user:'苏小',priority:'紧急',status:'处理中'},{id:'TK20260624',title:'接送车辆变更',user:'何言川',priority:'普通',status:'处理中'},{id:'TK20260625',title:'酒店房型升级',user:'周亦辰',priority:'普通',status:'已完成'}],
 roles:[{id:21,name:'超级管理员',members:1,permissions:allPermissions,locked:true},{id:22,name:'运营管理员',members:6,permissions:['景点查看','景点新增','景点编辑','订单查看','订单确认','游客查看','游客编辑','内容发布','内容编辑','工单受理','工单流转','数据大屏','数据导出']},{id:23,name:'产品经理',members:12,permissions:['景点查看','景点新增','景点编辑','订单查看','内容发布','内容编辑','数据大屏','数据导出']},{id:24,name:'客服专员',members:18,permissions:['订单查看','订单编辑','订单退款','游客查看','游客编辑','工单受理','工单流转']}]
}
const load=(k)=>JSON.parse(localStorage.getItem('travel-'+k)||JSON.stringify(defaults[k]))
const usersData=ref(load('users')),contents=ref(load('contents')),tickets=ref(load('tickets')),roles=ref(load('roles').map(r=>({...r,locked:r.name==='超级管理员',permissions:Array.isArray(r.permissions)?r.permissions:(r.name==='超级管理员'?allPermissions:allPermissions.slice(0,Math.min(r.permissions||6,allPermissions.length)))})))
const persist=()=>{localStorage.setItem('travel-users',JSON.stringify(usersData.value));localStorage.setItem('travel-contents',JSON.stringify(contents.value));localStorage.setItem('travel-tickets',JSON.stringify(tickets.value));localStorage.setItem('travel-roles',JSON.stringify(roles.value))}
const filteredUsers=computed(()=>usersData.value.filter(x=>x.name.includes(query.value)||x.phone.includes(query.value)))
const open=item=>{if(active.value==='角色权限'&&item?.locked)return ElMessage.warning('超级管理员为系统内置角色，权限不可修改');editing.value=item?{...item,permissions:Array.isArray(item.permissions)?[...item.permissions]:[]}:active.value==='游客管理'?{id:Date.now(),name:'',phone:'',level:'普通会员',trips:0,spent:0,status:'正常'}:active.value==='内容发布'?{id:Date.now(),title:'',type:'旅行攻略',views:'0',status:'草稿'}:active.value==='服务工单'?{id:'TK'+Date.now(),title:'',user:'',priority:'普通',status:'待受理'}:{id:Date.now(),name:'',members:0,permissions:['数据大屏']};dialog.value=true}
const collection=()=>active.value==='游客管理'?usersData.value:active.value==='内容发布'?contents.value:active.value==='服务工单'?tickets.value:roles.value
const save=()=>{const arr=collection(),i=arr.findIndex(x=>x.id===editing.value.id);i<0?arr.unshift({...editing.value}):arr.splice(i,1,{...editing.value});persist();dialog.value=false;ElMessage.success(`${active.value}数据已保存`)}
const remove=async item=>{if(active.value==='角色权限'&&item.locked)return ElMessage.warning('超级管理员受系统保护，不能删除');await ElMessageBox.confirm('删除后无法恢复，确定继续？','删除确认');const arr=collection(),i=arr.findIndex(x=>x.id===item.id);arr.splice(i,1);persist();ElMessage.success('记录已删除')}
const advance=t=>{t.status=t.status==='待受理'?'处理中':'已完成';persist();ElMessage.success('工单状态已流转')}
</script>
<template><div class="operations"><aside class="op-nav card"><small>运营控制台</small><button v-for="[x,icon] in menu" :class="{active:active===x}" @click="active=x"><component :is="icon"/>{{x}}<span>›</span></button><div><b>运营健康度</b><div class="health"><span>94</span></div><small>各项指标表现优秀</small></div></aside>
<section class="op-content card"><div class="op-head"><div><small>OPERATION CENTER</small><h2>{{active}}</h2><p>数据支持新增、查看、编辑、删除与状态流转</p></div><button class="primary-btn compact" @click="open()"><Plus/>新增{{active.replace('管理','').replace('发布','内容')}}</button></div>
<template v-if="active==='游客管理'"><div class="filter-line"><label class="search-box"><Search/><input v-model="query" placeholder="搜索游客姓名或手机号"/></label><span>注册游客 <b>{{usersData.length}}</b> 人</span></div><table class="data-table"><thead><tr><th>游客信息</th><th>会员等级</th><th>出行次数</th><th>累计消费</th><th>账号状态</th><th>操作</th></tr></thead><tbody><tr v-for="u in filteredUsers"><td><div class="avatar-name"><span>{{u.name[0]}}</span><div><b>{{u.name}}</b><small>{{u.phone}}</small></div></div></td><td><span class="level">{{u.level}}</span></td><td>{{u.trips}} 次</td><td><b>¥ {{u.spent.toLocaleString()}}</b></td><td><span class="status 已完成">{{u.status}}</span></td><td><button class="row-btn" @click="open(u)"><Pencil/></button><button class="row-btn danger" @click="remove(u)"><Trash2/></button></td></tr></tbody></table></template>
<template v-else-if="active==='内容发布'"><div class="content-grid"><article v-for="(x,i) in contents"><div :class="'content-cover c'+i"><FileText/></div><span>{{x.type}}</span><h3>{{x.title}}</h3><p>浏览 {{x.views}}</p><div><span :class="['status',x.status==='已发布'?'已完成':'待确认']">{{x.status}}</span><span><button class="row-btn" @click="open(x)"><Pencil/></button><button class="row-btn danger" @click="remove(x)"><Trash2/></button></span></div></article></div></template>
<template v-else-if="active==='服务工单'"><div class="ticket-board"><div v-for="(col,i) in ['待受理','处理中','已完成']"><h3><component :is="[AlertTriangle,Clock3,CheckCircle2][i]"/>{{col}}<span>{{tickets.filter(x=>x.status===col).length}}</span></h3><article v-for="item in tickets.filter(x=>x.status===col)"><small>#{{item.id}}</small><b>{{item.title}}</b><p>游客：{{item.user}} · 刚刚</p><span class="priority">{{item.priority}}</span><div class="ticket-actions"><button class="row-btn" @click="open(item)"><Pencil/></button><button v-if="item.status!=='已完成'" class="row-btn approve" @click="advance(item)"><CheckCircle2/></button><button class="row-btn danger" @click="remove(item)"><Trash2/></button></div></article></div></div></template>
<template v-else><div class="permission-note"><ShieldCheck/><div><b>基于角色的访问控制（RBAC）</b><p>权限精确到查看、新增、编辑、审批、退款、删除等操作；超级管理员拥有全部权限且不可修改。</p></div></div><div class="role-grid detailed"><div v-for="r in roles" :class="{locked:r.locked}"><span><ShieldCheck/></span><em v-if="r.locked">系统内置 · 已锁定</em><h3>{{r.name}}</h3><p>{{r.members}} 名成员 · {{r.permissions.length}} 项权限</p><div class="permission-tags"><i v-for="p in r.permissions.slice(0,4)">{{p}}</i><i v-if="r.permissions.length>4">+{{r.permissions.length-4}}</i></div><button :disabled="r.locked" @click="open(r)">{{r.locked?'不可修改':'配置权限'}}</button><button class="role-delete" :disabled="r.locked" @click="remove(r)">删除</button></div></div></template>
</section>
<el-dialog v-model="dialog" :title="`编辑${active}`" width="520px"><el-form v-if="editing" label-position="top">
 <template v-if="active==='游客管理'"><div class="form-two"><el-form-item label="游客姓名"><el-input v-model="editing.name"/></el-form-item><el-form-item label="手机号"><el-input v-model="editing.phone"/></el-form-item></div><div class="form-two"><el-form-item label="会员等级"><el-select v-model="editing.level"><el-option v-for="x in ['普通会员','银卡会员','金卡会员','星耀会员']" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="editing.status"><el-option label="正常" value="正常"/><el-option label="关注" value="关注"/><el-option label="禁用" value="禁用"/></el-select></el-form-item></div><div class="form-two"><el-form-item label="出行次数"><el-input-number v-model="editing.trips"/></el-form-item><el-form-item label="累计消费"><el-input-number v-model="editing.spent"/></el-form-item></div></template>
 <template v-else-if="active==='内容发布'"><el-form-item label="内容标题"><el-input v-model="editing.title"/></el-form-item><div class="form-two"><el-form-item label="内容分类"><el-input v-model="editing.type"/></el-form-item><el-form-item label="发布状态"><el-select v-model="editing.status"><el-option label="草稿" value="草稿"/><el-option label="已发布" value="已发布"/></el-select></el-form-item></div></template>
 <template v-else-if="active==='服务工单'"><el-form-item label="工单主题"><el-input v-model="editing.title"/></el-form-item><div class="form-two"><el-form-item label="游客"><el-input v-model="editing.user"/></el-form-item><el-form-item label="优先级"><el-select v-model="editing.priority"><el-option label="普通" value="普通"/><el-option label="紧急" value="紧急"/></el-select></el-form-item></div><el-form-item label="处理状态"><el-radio-group v-model="editing.status"><el-radio-button v-for="x in ['待受理','处理中','已完成']" :label="x" :value="x"/></el-radio-group></el-form-item></template>
 <template v-else><el-form-item label="角色名称"><el-input v-model="editing.name"/></el-form-item><el-form-item label="成员数量"><el-input-number v-model="editing.members"/></el-form-item><div class="permission-editor"><section v-for="g in permissionGroups"><h4>{{g.name}}</h4><el-checkbox-group v-model="editing.permissions"><el-checkbox v-for="p in g.items" :label="p" :value="p">{{p}}</el-checkbox></el-checkbox-group></section></div><div class="selected-count">已选择 {{editing.permissions.length}} / {{allPermissions.length}} 项权限</div></template>
</el-form><template #footer><button class="outline-btn" @click="dialog=false">取消</button><button class="primary-btn compact" @click="save"><Send/>保存数据</button></template></el-dialog></div></template>
