<script setup>
import {ref,computed} from 'vue'
import {Sparkles,MapPin,CalendarDays,Users,Wallet,Utensils,Camera,Mountain,Bus,Clock3,ArrowRight,RefreshCw,Download,CheckCircle2,MoonStar} from 'lucide-vue-next'
import {ElMessage} from 'element-plus'
import {generateAITravel} from '../services/aiTravel'
const city=ref('杭州'),days=ref(3),people=ref(2),budget=ref('舒适'),prefs=ref(['自然风光','人文历史']),loading=ref(false),generated=ref(false),result=ref(null),stage=ref('分析旅行偏好')
const tags=['自然风光','人文历史','城市漫游','特色美食','亲子互动','户外探险']
const colors=['#16b8a6','#7c6cf2','#f59e0b','#f25f7b','#3b82f6','#8b5cf6','#14b8a6']
const icons={sight:Mountain,food:Utensils,photo:Camera,night:MoonStar,transport:Bus}
const totalItems=computed(()=>result.value?.days.reduce((n,d)=>n+d.items.length,0)||0)
const generate=async()=>{loading.value=true;generated.value=false;const stages=['分析旅行偏好','匹配实时热门景点','优化交通与游玩动线','计算预算与时间'];let i=0;stage.value=stages[0];const timer=setInterval(()=>stage.value=stages[++i%stages.length],900);result.value=await generateAITravel({city:city.value,days:days.value,people:people.value,budget:budget.value,prefs:prefs.value});clearInterval(timer);loading.value=false;generated.value=true;ElMessage.success(`已生成完整 ${result.value.days.length} 日行程`)}
const toggle=t=>prefs.value.includes(t)?prefs.value=prefs.value.filter(x=>x!==t):prefs.value.push(t)
</script>
<template><div class="planner-page"><section class="planner-hero card"><div class="ai-badge"><span></span><Sparkles :size="16"/>TRAVELSPARK AI · FREE API</div><h2>一句话，生成你的理想旅程</h2><p>选择几天，就生成几天完整安排；融合兴趣偏好、游玩节奏与预算。</p><div class="planner-form"><label><MapPin/><span>想去哪里<el-select v-model="city"><el-option v-for="c in ['杭州','西安','厦门','丽江','北京']" :label="c" :value="c"/></el-select></span></label><i></i><label><CalendarDays/><span>游玩天数<el-input-number v-model="days" :min="1" :max="7"/></span></label><i></i><label><Users/><span>出行人数<el-input-number v-model="people" :min="1" :max="10"/></span></label><i></i><label><Wallet/><span>预算偏好<el-select v-model="budget"><el-option v-for="b in ['经济','舒适','品质','奢享']" :label="b" :value="b"/></el-select></span></label></div><div class="preference"><span>旅行偏好</span><button v-for="t in tags" :class="{active:prefs.includes(t)}" @click="toggle(t)">{{t}}</button></div><button class="generate-btn" @click="generate" :disabled="loading"><span class="shine"></span><RefreshCw v-if="loading" class="spin"/><Sparkles v-else/>{{loading?stage:'AI 生成 '+days+' 日专属行程'}}<ArrowRight v-if="!loading"/></button></section>
<transition name="reveal"><section v-if="generated&&result" class="plan-result"><div class="result-head"><div><span><CheckCircle2/>行程生成完成 · {{result.source}}</span><h2>{{result.title}}</h2><p>{{people}} 人 · {{days}} 天 · {{totalItems}} 项安排 · 匹配度 <b>96%</b></p></div><div><button class="outline-btn"><Download/>导出行程单</button><button class="primary-btn compact" @click="generate"><RefreshCw/>重新规划</button></div></div><div class="plan-layout"><div class="timeline card"><article v-for="(p,index) in result.days" :key="p.day" :style="{'--day-color':colors[index%colors.length]}"><div class="day-label"><b>DAY {{String(p.day).padStart(2,'0')}}</b><span></span></div><div class="day-content"><h3>{{p.title}}</h3><div v-for="it in p.items" class="plan-item"><time>{{it.time}}</time><span><component :is="icons[it.type]||MapPin"/></span><div><b>{{it.name}}</b><small>{{it.detail}}</small></div><Clock3 class="clock"/></div></div></article></div><aside><div class="card cost-card"><small>AI 预算估算</small><h3>¥ {{Number(result.estimatedCost||days*people*680).toLocaleString()}}</h3><p>人均约 ¥{{Math.round((result.estimatedCost||days*people*680)/people).toLocaleString()}}</p><div><span>住宿 42%</span><i><b style="width:42%;background:#7c6cf2"></b></i><span>交通 23%</span><i><b style="width:23%;background:#16b8a6"></b></i><span>餐饮 20%</span><i><b style="width:20%;background:#f59e0b"></b></i><span>门票 15%</span><i><b style="width:15%;background:#fb7185"></b></i></div></div><div class="card map-mini"><div class="map-lines"><i></i><i></i><i></i><span>1</span><span>2</span><span>{{days}}</span></div><b>{{days}} 日路线已优化</b><small>{{result.summary}}</small></div></aside></div></section></transition>
<section v-if="!generated" class="empty-ai"><div><Sparkles/></div><h3>你的 {{days}} 日惊喜行程将在这里出现</h3><p>完善旅行偏好，AI 将为你规划每日路线、时间与预算</p></section></div></template>
