<script setup>
import {ref,computed} from 'vue'
import {useRouter} from 'vue-router'
import {MapPin,Search,CalendarDays,Heart,UserRound,Compass,Sparkles,Sun,ArrowRight,Clock3,Star,LogOut,TicketCheck} from 'lucide-vue-next'
import {destinations} from '../data/mock'
import {ElMessage} from 'element-plus'
import CatCompanion from '../components/CatCompanion.vue'
import WorldExplorer from '../components/WorldExplorer.vue'
import DestinationApiInsights from '../components/DestinationApiInsights.vue'
import ApiCommandCenter from '../components/ApiCommandCenter.vue'
const router=useRouter(),account=localStorage.getItem('travel-account')||'traveler',userName=ref(localStorage.getItem('travel-user')||'旅行者'),tab=ref('发现'),city=ref('杭州'),days=ref(3),showPlan=ref(false),selected=ref(null),savedPlan=ref(JSON.parse(localStorage.getItem(`travel-plan-${localStorage.getItem('travel-account')||'traveler'}`)||'null'))
const profile=computed(()=>{if(account==='traveler')return{level:'星耀会员',points:8620,trips:12,spent:28680,favorites:8,badges:6,memberCode:'STAR MEMBER'};const accounts=JSON.parse(localStorage.getItem('travel-accounts')||'[]'),users=JSON.parse(localStorage.getItem('travel-users')||'[]'),data=users.find(x=>x.account===account)||accounts.find(x=>x.account===account)||{};return{level:data.level||'普通会员',points:data.points||0,trips:data.trips||0,spent:data.spent||0,favorites:data.favorites||0,badges:data.badges??1,memberCode:'NEW MEMBER'}})
const liked=ref(profile.value.favorites?[2]:[])
const accountRecord=JSON.parse(localStorage.getItem('travel-accounts')||'[]').find(x=>x.account===account)||JSON.parse(localStorage.getItem('travel-users')||'[]').find(x=>x.account===account)||{}
const profileForm=ref({name:userName.value,phone:accountRecord.phone||'',gender:accountRecord.gender||'保密',birthday:accountRecord.birthday||'',homeCity:accountRecord.homeCity||'杭州',bio:accountRecord.bio||'世界很大，下一站正在计划中。'})
const routeDetails={
 '西湖风景名胜区':['断桥残雪晨间漫步','白堤—平湖秋月骑行','曲院风荷午间休憩','苏堤春晓落日摄影','湖滨音乐喷泉夜游'],
 '故宫博物院':['午门安检与检票','太和殿中轴线讲解','乾清宫—御花园深游','珍宝馆专题参观','神武门文创体验'],
 '玉龙雪山':['游客中心领取装备','冰川公园索道上山','海拔4506观景台打卡','蓝月谷环保车环游','甘海子日落返程'],
 '鼓浪屿':['邮轮中心验票登船','三丘田码头登陆','最美转角建筑漫游','菽庄花园与钢琴博物馆','龙头路美食与日落返航']
}
const journeySteps=computed(()=>{if(!selected.value)return[];const d=selected.value,spots=routeDetails[d.name]||['游客中心集合','核心景区游览','特色体验项目','最佳机位摄影','游客中心返程'];return[
 {time:'出发前 1 天',title:'行前确认',detail:`确认${d.name}开放状态、天气与携带物品，系统推送电子行程单。`,state:'待准备'},
 {time:'08:00',title:'交通出发',detail:`从酒店出发，导航前往${d.city}景区入口，预计交通 35 分钟。`,state:'导航'},
 {time:'08:45',title:'预约核验与入园',detail:`出示电子凭证完成实名核验，${d.price?'门票 ¥'+d.price:'无需购买门票'}。`,state:'凭证'},
 ...spots.map((name,i)=>({time:['09:00','10:20','12:00','14:10','16:40'][i],title:name,detail:['避开早高峰，跟随推荐路线进入核心景观。','开启语音讲解，了解目的地历史与文化。','品尝当地特色午餐并休整补给。','参与在地体验，系统自动记录旅行足迹。','抵达最佳观景点，完成今日旅行打卡。'][i],state:i===2?'餐饮':'游览'})),
 {time:'18:00',title:'返程与订单归档',detail:'导航返回酒店，交通与门票凭证自动归入本次旅行订单。',state:'返程'},
 {time:'旅行结束',title:'评价与生成游记',detail:'提交评分后获得旅行值，AI 自动整理照片与足迹生成旅行游记。',state:'完成'}]})
const logout=()=>{localStorage.removeItem('travel-token');localStorage.removeItem('travel-role');router.push('/login')}
const toggle=id=>{liked.value=liked.value.includes(id)?liked.value.filter(x=>x!==id):[...liked.value,id]}
const createPlan=()=>{selected.value=destinations.find(d=>d.city===city.value)||destinations[0];planDestination()}
const openDestination=d=>selected.value=d
const planDestination=()=>{if(!selected.value)return;const destination={...selected.value},steps=journeySteps.value.map(x=>({...x}));city.value=destination.city;savedPlan.value={id:'AI'+Date.now(),title:`${destination.city} · ${destination.name}完整旅行`,destination,steps,createdAt:new Date().toLocaleString('zh-CN'),status:'AI 已生成',total:'10 小时',distance:'约 26 km'};localStorage.setItem(`travel-plan-${account}`,JSON.stringify(savedPlan.value));selected.value=null;showPlan.value=false;tab.value='我的行程';ElMessage.success(`${destination.name}完整行程已立即生成`)}
const saveProfile=()=>{const f=profileForm.value;if(!f.name.trim())return ElMessage.warning('昵称不能为空');if(f.phone&&!/^1\d{10}$/.test(f.phone))return ElMessage.warning('请输入正确的手机号');const accounts=JSON.parse(localStorage.getItem('travel-accounts')||'[]'),ai=accounts.findIndex(x=>x.account===account);if(ai>=0)accounts[ai]={...accounts[ai],...f};else if(account!=='traveler')accounts.push({account,role:'visitor',...f});localStorage.setItem('travel-accounts',JSON.stringify(accounts));const users=JSON.parse(localStorage.getItem('travel-users')||'[]'),ui=users.findIndex(x=>x.account===account||x.name===userName.value);const record={id:ui>=0?users[ui].id:Date.now(),account,name:f.name,phone:f.phone,gender:f.gender,birthday:f.birthday,homeCity:f.homeCity,bio:f.bio,level:profile.value.level,points:profile.value.points,trips:profile.value.trips,spent:profile.value.spent,favorites:profile.value.favorites,badges:profile.value.badges,status:'正常'};ui>=0?users.splice(ui,1,record):users.push(record);localStorage.setItem('travel-users',JSON.stringify(users));userName.value=f.name;localStorage.setItem('travel-user',f.name);ElMessage.success('个人资料已保存并同步')}
</script>
<template><div class="visitor-page"><header class="visitor-nav"><div class="visitor-brand"><div class="brand-mark"><span></span><i></i></div><b>云迹</b><small>去遇见世界</small></div><nav><button v-for="x in ['发现','目的地','我的行程','旅行订单','个人资料']" :class="{active:tab===x}" @click="tab=x">{{x}}</button></nav><div><label><Search/><input placeholder="搜索旅行灵感"/></label><button class="visitor-avatar" title="个人资料" @click="tab='个人资料'">{{userName.slice(0,1)}}</button><button class="visitor-logout" @click="logout"><LogOut/></button></div></header>
<main class="visitor-main"><section class="visitor-hero"><div class="visitor-sun"><Sun/></div><div class="visitor-copy"><span><Sparkles/>TRAVELSPARK AI</span><h1>你好，{{userName}}<br/>下一站，去哪里？</h1><p>盛夏的风正吹向山海，世界在等你出发。</p><div class="quick-plan"><label><MapPin/><span>出发目的地<el-select v-model="city"><el-option v-for="x in ['杭州','西安','厦门','丽江','北京']" :label="x" :value="x"/></el-select></span></label><label><CalendarDays/><span>游玩天数<el-input-number v-model="days" :min="1" :max="7"/></span></label><button @click="createPlan"><Sparkles/>AI 规划旅程</button></div></div><div class="hero-landscape"><i class="hill h1"></i><i class="hill h2"></i><span class="traveler">♙</span><div class="floating-card"><small>今日旅行灵感</small><b>西湖晚霞指数 98%</b><span>18:42 日落 · 适合拍照</span></div></div></section>
<CatCompanion v-if="tab==='发现'||tab==='目的地'"/><WorldExplorer v-if="tab==='发现'||tab==='目的地'"/><ApiCommandCenter v-if="tab==='发现'||tab==='目的地'"/><section v-if="showPlan" class="visitor-plan"><div><span>AI PLAN · {{days}} DAYS</span><h2>{{city}}湖山漫游计划已就绪</h2><p>西湖骑行 → 灵隐寻幽 → 龙井问茶 → 运河夜游</p></div><button @click="tab='我的行程'">查看完整行程<ArrowRight/></button></section>
<section v-if="tab==='发现'||tab==='目的地'"><div class="visitor-heading"><div><span>CURATED FOR YOU</span><h2>为你精选的旅行灵感</h2><p>根据你的收藏和历史行程智能推荐</p></div><button>查看全部 <ArrowRight/></button></div><div class="visitor-destinations"><article v-for="d in destinations.slice(0,4)" :style="{'--c':d.color}" tabindex="0" @click="openDestination(d)" @keydown.enter="openDestination(d)"><div class="visitor-scene"><span>{{d.city}}</span><button @click.stop="toggle(d.id)" :class="{liked:liked.includes(d.id)}"><Heart :fill="liked.includes(d.id)?'currentColor':'none'"/></button><i></i><i></i><em>点击探索</em></div><div><small>{{d.category}} · {{d.tag}}</small><h3>{{d.name}}</h3><p>{{d.desc}}</p><footer><span><Star fill="#fbbf24"/>{{d.score}}</span><span><Clock3/>建议 3-4 小时</span><b>{{d.price?'¥'+d.price+' 起':'免费'}}</b></footer></div></article></div></section>
<section v-else-if="tab==='我的行程'" class="visitor-account generated-account"><div v-if="savedPlan" class="trip-card generated-trip"><div class="generated-trip-head"><div><span>AI JOURNEY · {{savedPlan.status}}</span><h2>{{savedPlan.title}}</h2><p>创建于 {{savedPlan.createdAt}} · 行程编号 {{savedPlan.id}}</p></div><em>{{savedPlan.steps.length}} 个环节</em></div><div class="generated-route"><article v-for="(step,index) in savedPlan.steps"><time>{{step.time}}</time><i>{{index+1}}</i><div><b>{{step.title}}</b><small>{{step.detail}}</small></div><span>{{step.state}}</span></article></div><footer><div><b>{{savedPlan.total}}</b><small>预计时长</small></div><div><b>{{savedPlan.distance}}</b><small>交通距离</small></div><div><b>+120</b><small>完成奖励</small></div><button><Compass/>打开行程导航</button></footer></div><div v-else class="trip-card new-member-empty"><span>START YOUR FIRST TRIP</span><h2>开启你的第一次云迹旅行</h2><p>当前还没有行程，使用 AI 规划即可快速创建。</p><button @click="tab='发现'"><Sparkles/>立即规划行程</button></div><div class="member-card"><div class="member-top"><span>{{account.toUpperCase()}}</span><b>{{profile.memberCode}}</b></div><h3>{{profile.level}}</h3><p>旅行值 {{profile.points.toLocaleString()}}</p><div><span>{{profile.trips}}<b>旅行次数</b></span><span>{{profile.favorites}}<b>收藏目的地</b></span><span>{{profile.badges}}<b>旅行勋章</b></span></div></div></section>
<section v-else-if="tab==='旅行订单'" class="visitor-orders"><div class="visitor-heading"><div><span>MY ORDERS</span><h2>旅行订单</h2></div></div><div v-if="profile.trips" class="visitor-order-card"><span><TicketCheck/></span><div><small>YJ20260622001</small><h3>杭州·西湖宋韵三日游</h3><p>2026.07.12 出发 · 2人</p></div><b>¥ 2,399</b><em>待出行</em><button>查看详情</button></div><div v-else class="visitor-empty-order"><TicketCheck/><h3>还没有旅行订单</h3><p>选择心仪目的地，开始你的第一次旅行。</p><button @click="tab='发现'">去发现旅行灵感</button></div></section>
<section v-else class="profile-center"><div class="profile-banner"><div class="profile-big-avatar">{{userName.slice(0,1)}}</div><div><span>TRAVELER PROFILE</span><h2>{{userName}}</h2><p>{{profile.level}} · 旅行值 {{profile.points.toLocaleString()}}</p></div><div class="profile-level"><b>{{profile.trips}}</b><small>旅行次数</small></div><div class="profile-level"><b>{{profile.badges}}</b><small>旅行勋章</small></div></div><div class="profile-layout"><form class="profile-form-card" @submit.prevent="saveProfile"><div class="profile-title"><div><h3>基本资料</h3><p>修改后将同步到会员卡和后台游客管理</p></div><span>账号 {{account}}</span></div><div class="profile-form-grid"><label>昵称 / 姓名<input v-model.trim="profileForm.name" maxlength="20"/></label><label>手机号码<input v-model.trim="profileForm.phone" maxlength="11" placeholder="请输入手机号"/></label><label>性别<el-select v-model="profileForm.gender"><el-option v-for="x in ['保密','男','女']" :label="x" :value="x"/></el-select></label><label>出生日期<el-date-picker v-model="profileForm.birthday" value-format="YYYY-MM-DD" placeholder="选择日期"/></label><label>常住城市<el-select v-model="profileForm.homeCity" filterable allow-create><el-option v-for="x in ['杭州','上海','北京','成都','西安','厦门','广州','丽江']" :label="x" :value="x"/></el-select></label><label class="profile-bio">个人简介<el-input v-model="profileForm.bio" type="textarea" :rows="4" maxlength="100" show-word-limit/></label></div><button class="profile-save"><UserRound/>保存个人资料</button></form><aside class="profile-side"><div><span>会员成长</span><h3>{{profile.level}}</h3><p>再获得 {{Math.max(0,3000-profile.points)}} 旅行值可升级下一等级</p><i><b :style="{width:Math.min(100,profile.points/30)+'%'}"></b></i></div><div><span>账号安全</span><p><b>登录密码</b><small>已设置</small></p><p><b>手机验证</b><small>{{profileForm.phone?'已绑定':'未绑定'}}</small></p><p><b>数据同步</b><small>正常</small></p></div></aside></div></section>
</main><el-drawer v-model="selected" size="560px" :show-close="false" class="destination-detail"><template #header><div class="detail-drawer-head"><span>COMPLETE JOURNEY · 全流程</span><button @click="selected=null">×</button></div></template><div v-if="selected" class="destination-detail-body"><div class="detail-cover" :style="{'--detail-color':selected.color}"><span>{{selected.city}}</span><i></i><div><b>{{selected.tag}}</b><small>热度指数 {{selected.heat}}</small></div></div><span class="detail-category">{{selected.category}}</span><h2>{{selected.name}}</h2><p>{{selected.desc}}</p><div class="detail-metrics"><div><Star fill="#fbbf24"/><b>{{selected.score}}</b><small>游客评分</small></div><div><Clock3/><b>约 10h</b><small>完整过程</small></div><div><TicketCheck/><b>{{selected.price?'¥'+selected.price:'免费'}}</b><small>参考门票</small></div></div><DestinationApiInsights :destination="selected"/><section class="detail-highlights"><h3>体验亮点</h3><div><span>01</span><p><b>城市代表性景观</b><small>精选最佳游览路线与拍摄机位</small></p></div><div><span>02</span><p><b>在地文化体验</b><small>深入当地历史、人文与生活方式</small></p></div><div><span>03</span><p><b>智能避峰建议</b><small>结合实时热度推荐舒适游览时段</small></p></div></section><section class="complete-journey"><div class="journey-title"><div><span>FULL DAY TIMELINE</span><h3>完整旅行过程</h3></div><em>{{journeySteps.length}} 个环节</em></div><article v-for="(step,index) in journeySteps" :class="{done:index===journeySteps.length-1}"><div class="journey-time">{{step.time}}</div><span class="journey-dot">{{String(index+1).padStart(2,'0')}}</span><div><b>{{step.title}}</b><p>{{step.detail}}</p><small>{{step.state}}</small></div></article></section><div class="journey-summary"><span><b>预计总时长</b><small>10 小时</small></span><span><b>交通距离</b><small>约 26 km</small></span><span><b>旅行值奖励</b><small>+120</small></span></div><div class="detail-actions sticky"><button @click="toggle(selected.id)"><Heart :fill="liked.includes(selected.id)?'currentColor':'none'"/>{{liked.includes(selected.id)?'已收藏':'收藏目的地'}}</button><button @click="planDestination"><Sparkles/>AI 规划完整行程</button></div></div></el-drawer></div></template>
