<script setup>
import {ref,watch,computed} from 'vue'
import {BookOpen,Sunrise,Sunset,Clock3,Camera,ExternalLink,CloudSun} from 'lucide-vue-next'
const props=defineProps({destination:Object})
const coords={'西湖风景名胜区':[30.2448,120.1500],'故宫博物院':[39.9163,116.3972],'玉龙雪山':[27.0985,100.1751],'鼓浪屿':[24.4471,118.0633],'大唐不夜城':[34.2180,108.9584],'张家界国家森林公园':[29.3250,110.4340]}
const wikiTitle={'西湖风景名胜区':'西湖','故宫博物院':'故宫博物院','玉龙雪山':'玉龙雪山','鼓浪屿':'鼓浪屿'}
const intros={'西湖':'西湖位于浙江省杭州市，是中国首批国家重点风景名胜区。湖区以“一山、二塔、三岛、三堤、五湖”为格局，苏堤春晓、断桥残雪等景观共同构成独特的江南山水画卷。','故宫博物院':'故宫博物院建立于1925年，位于北京故宫紫禁城内，是在明清皇宫及其收藏基础上建立的大型综合性博物馆。','玉龙雪山':'玉龙雪山位于云南省丽江市，是北半球纬度最低、终年积雪的山脉之一，也是纳西族文化中的神山。','鼓浪屿':'鼓浪屿位于福建省厦门市，以历史国际社区、近代建筑群和音乐文化闻名，2017年列入世界文化遗产名录。'}
const wiki=ref(null),sun=ref(null),loading=ref(false),error=ref(false)
const time=t=>t?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t)):'--'
const daylight=computed(()=>{const s=sun.value?.day_length;if(!s)return'--';return`${Math.floor(s/3600)}小时${Math.round(s%3600/60)}分`})
const golden=computed(()=>{if(!sun.value)return'--';const d=new Date(sun.value.sunset);d.setMinutes(d.getMinutes()-55);return time(d)})
const load=async()=>{if(!props.destination)return;loading.value=true;error.value=false;const [lat,lng]=coords[props.destination.name]||[30.2741,120.1551],title=wikiTitle[props.destination.name]||props.destination.name;wiki.value={title,extract:intros[title]||`${title}是本次智能行程中的核心目的地，系统将结合实时天气、光照与路线数据生成游览建议。`,content_urls:{desktop:{page:`https://zh.wikipedia.org/wiki/${encodeURIComponent(title)}`}}};const params=new URLSearchParams({action:'query',prop:'extracts|pageimages',exintro:'1',explaintext:'1',piprop:'thumbnail',pithumbsize:'500',redirects:'1',titles:title,format:'json',origin:'*'});const [w,s]=await Promise.allSettled([fetch(`/api/wiki?${params}`).then(r=>{if(!r.ok)throw 0;return r.json()}),fetch(`/api/sun?lat=${lat}&lng=${lng}&formatted=0`).then(r=>{if(!r.ok)throw 0;return r.json()})]);if(w.status==='fulfilled'){const page=Object.values(w.value.query?.pages||{})[0];if(page?.extract)wiki.value={title:page.title||title,extract:page.extract,thumbnail:page.thumbnail,content_urls:{desktop:{page:`https://zh.wikipedia.org/wiki/${encodeURIComponent(page.title||title)}`}}}}if(s.status==='fulfilled')sun.value=s.value.results;else error.value=true;loading.value=false}
watch(()=>props.destination?.id,load,{immediate:true})
</script>
<template><section class="destination-api" :class="{loading}"><header><div><span><CloudSun/>LIVE DESTINATION DATA</span><h3>实时百科与光线情报</h3></div><em><i></i>{{error?'备用数据':'API 已连接'}}</em></header><div class="sun-grid"><div><Sunrise/><span><small>今日日出</small><b>{{time(sun?.sunrise)}}</b></span></div><div><Sunset/><span><small>今日日落</small><b>{{time(sun?.sunset)}}</b></span></div><div><Clock3/><span><small>白昼时长</small><b>{{daylight}}</b></span></div><div class="golden"><Camera/><span><small>黄金拍摄时间</small><b>{{golden}} 前后</b></span></div></div><article v-if="wiki"><div v-if="wiki.thumbnail" class="wiki-thumb"><img :src="wiki.thumbnail.source"/></div><div><span><BookOpen/>WIKIPEDIA 中文百科</span><h4>{{wiki.title}}</h4><p>{{wiki.extract}}</p><a :href="wiki.content_urls?.desktop?.page" target="_blank">阅读完整词条 <ExternalLink/></a></div></article><div v-else class="api-skeleton"><i></i><i></i><i></i></div></section></template>
