<script setup>
import {ref,computed,onMounted} from 'vue'
import {Globe2,Landmark,Coins,Languages,Users,Map,RefreshCw,ArrowUpRight} from 'lucide-vue-next'
import {ElMessage} from 'element-plus'
const options=[['JP','日本','Japan','Asia/Tokyo','日语','东亚'],['FR','法国','France','Europe/Paris','法语','西欧'],['IT','意大利','Italy','Europe/Rome','意大利语','南欧'],['TH','泰国','Thailand','Asia/Bangkok','泰语','东南亚'],['IS','冰岛','Iceland','Atlantic/Reykjavik','冰岛语','北欧'],['AU','澳大利亚','Australia','Australia/Sydney','英语','大洋洲'],['EG','埃及','Egypt','Africa/Cairo','阿拉伯语','北非'],['NZ','新西兰','New Zealand','Pacific/Auckland','英语、毛利语','大洋洲']]
const fallback={JP:['东京','JPY','https://flagcdn.com/w320/jp.png',124500000],FR:['巴黎','EUR','https://flagcdn.com/w320/fr.png',68400000],IT:['罗马','EUR','https://flagcdn.com/w320/it.png',58900000],TH:['曼谷','THB','https://flagcdn.com/w320/th.png',71600000],IS:['雷克雅未克','ISK','https://flagcdn.com/w320/is.png',393000],AU:['堪培拉','AUD','https://flagcdn.com/w320/au.png',27300000],EG:['开罗','EGP','https://flagcdn.com/w320/eg.png',114500000],NZ:['惠灵顿','NZD','https://flagcdn.com/w320/nz.png',5300000]}
const code=ref('JP'),country=ref(null),loading=ref(false)
const option=computed(()=>options.find(x=>x[0]===code.value)||options[0])
const localTime=computed(()=>new Intl.DateTimeFormat('zh-CN',{timeZone:option.value[3],hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()))
const call=(endpoint,name)=>fetch(`/api/countriesnow/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({country:name})}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})
const load=async()=>{loading.value=true;const name=option.value[2],cached=fallback[code.value];country.value={name:option.value[1],english:name,capital:cached[0],currency:cached[1],flag:cached[2],population:cached[3],populationYear:2025,language:option.value[4],region:option.value[5]};try{const [capital,currency,flag,population]=await Promise.all([call('capital',name),call('currency',name),call('flag/images',name),call('population',name)]);const counts=population.data?.populationCounts||[],latest=counts[counts.length-1];if(capital.data?.capital)country.value={...country.value,capital:capital.data.capital,currency:currency.data?.currency||cached[1],flag:flag.data?.flag||cached[2],population:latest?.value||cached[3],populationYear:latest?.year||2025}}catch(e){ElMessage.info('云端限流，已展示本地缓存资料')}finally{loading.value=false}}
const random=()=>{let next;do{next=options[Math.floor(Math.random()*options.length)][0]}while(next===code.value);code.value=next;load()}
onMounted(load)
</script>
<template><section class="world-explorer"><div class="world-map-art"><div class="world-grid"></div><Globe2/><span v-for="n in 9" :style="{left:(9+n*9)+'%',top:(22+(n*17)%58)+'%'}"></span><div class="world-live"><i></i>COUNTRIESNOW · 4 API LIVE</div></div><div class="world-content"><header><div><span>WORLD DISCOVERY LAB</span><h2>国家旅行探索实验室</h2><p>四组云端接口联合读取首都、国旗、货币与人口信息。</p></div><div><el-select v-model="code" @change="load"><el-option v-for="o in options" :label="o[1]" :value="o[0]"/></el-select><button @click="random"><RefreshCw :class="{spin:loading}"/>随机探索</button></div></header><div v-if="country" class="country-card" :class="{loading}"><div class="country-identity"><img :src="country.flag" :alt="country.name+'国旗'"/><div><small>{{code}} · {{country.region}}</small><h3>{{country.name}}</h3><p>{{country.english}}</p></div><b>{{localTime}}<small>当地时间</small></b></div><div class="country-facts"><div><Landmark/><span><small>首都</small><b>{{country.capital||'--'}}</b></span></div><div><Coins/><span><small>货币代码</small><b>{{country.currency||'--'}}</b></span></div><div><Languages/><span><small>主要语言</small><b>{{country.language}}</b></span></div><div><Users/><span><small>{{country.populationYear}} 人口</small><b>{{(country.population/10000).toFixed(1)}} 万</b></span></div><div><Map/><span><small>所在区域</small><b>{{country.region}}</b></span></div></div><footer><span>旅行灵感：探索 {{country.capital}} 的城市文化与在地生活</span><button>生成国际行程<ArrowUpRight/></button></footer></div><div v-else class="country-loading"><RefreshCw class="spin"/>正在组合四组国家数据…</div></div></section></template>
