import { createApp } from 'vue'
import { createPinia } from 'pinia'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import './styles.css'
import './styles2.css'
import './styles3.css'
import './styles4.css'
import './visitor.css'
import './search.css'
import './auth.css'
import './pulse.css'
import './visitor2.css'
import './visitor3.css'
import './visitor4.css'
import './visitor5.css'
import './visitor6.css'
import './cat.css'
import './voice.css'
import './explorer.css'
import App from './App.vue'
import router from './router'
createApp(App).use(createPinia()).use(router).use(ElementPlus).mount('#app')
